-- MySQL Script generated by MySQL Workbench
-- Út 1. listopadu 2022, 20:29:25
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`univerzita`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`univerzita` (
  `id` INT NOT NULL,
  `nazev` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`fakulta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`fakulta` (
  `id` INT NOT NULL,
  `nazev` VARCHAR(60) NULL,
  `univerzita_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_fakulta_univerzita1_idx` (`univerzita_id` ASC) VISIBLE,
  CONSTRAINT `fk_fakulta_univerzita1`
    FOREIGN KEY (`univerzita_id`)
    REFERENCES `mydb`.`univerzita` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`clovek`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`clovek` (
  `id` INT NOT NULL,
  `jmeno` VARCHAR(45) NULL,
  `prijmeni` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`titul`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`titul` (
  `id` INT NOT NULL,
  `titul` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`pozice`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`pozice` (
  `id` INT NOT NULL,
  `pozice` VARCHAR(45) NULL DEFAULT 'učitel',
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`clovek_has_pozice`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`clovek_has_pozice` (
  `clovek_id` INT NOT NULL,
  `pozice_id` INT NOT NULL,
  PRIMARY KEY (`clovek_id`, `pozice_id`),
  INDEX `fk_clovek_has_pozice_pozice1_idx` (`pozice_id` ASC) VISIBLE,
  INDEX `fk_clovek_has_pozice_clovek_idx` (`clovek_id` ASC) VISIBLE,
  CONSTRAINT `fk_clovek_has_pozice_clovek`
    FOREIGN KEY (`clovek_id`)
    REFERENCES `mydb`.`clovek` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_clovek_has_pozice_pozice1`
    FOREIGN KEY (`pozice_id`)
    REFERENCES `mydb`.`pozice` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`clovek_has_titul`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`clovek_has_titul` (
  `clovek_id` INT NOT NULL,
  `titul_id` INT NOT NULL,
  PRIMARY KEY (`clovek_id`, `titul_id`),
  INDEX `fk_clovek_has_titul_titul1_idx` (`titul_id` ASC) VISIBLE,
  INDEX `fk_clovek_has_titul_clovek1_idx` (`clovek_id` ASC) VISIBLE,
  CONSTRAINT `fk_clovek_has_titul_clovek1`
    FOREIGN KEY (`clovek_id`)
    REFERENCES `mydb`.`clovek` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_clovek_has_titul_titul1`
    FOREIGN KEY (`titul_id`)
    REFERENCES `mydb`.`titul` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`fakulta_has_clovek`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`fakulta_has_clovek` (
  `fakulta_id` INT NOT NULL,
  `clovek_id` INT NOT NULL,
  PRIMARY KEY (`fakulta_id`, `clovek_id`),
  INDEX `fk_fakulta_has_clovek_clovek1_idx` (`clovek_id` ASC) VISIBLE,
  INDEX `fk_fakulta_has_clovek_fakulta1_idx` (`fakulta_id` ASC) VISIBLE,
  CONSTRAINT `fk_fakulta_has_clovek_fakulta1`
    FOREIGN KEY (`fakulta_id`)
    REFERENCES `mydb`.`fakulta` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_fakulta_has_clovek_clovek1`
    FOREIGN KEY (`clovek_id`)
    REFERENCES `mydb`.`clovek` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
