-- MySQL Script generated by MySQL Workbench
-- Čt 20. října 2022, 20:35:45
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema nsql
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema nsql
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `nsql` ;
USE `nsql` ;

-- -----------------------------------------------------
-- Table `nsql`.`login`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `nsql`.`login` (
  `username` VARCHAR(60) NOT NULL,
  `password` VARCHAR(60) NULL,
  PRIMARY KEY (`username`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
